name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: booking
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium

    - name: Copy .env file
      run: cp .env.example .env

    - name: Start Docker containers
      run: |
        docker-compose up -d
        # Wait for containers to be healthy
        sleep 30

    - name: Run database migrations and seeding
      run: |
        docker-compose exec -T php-fpm php artisan migrate:fresh --seed
        docker-compose exec -T php-fpm php artisan key:generate

    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true

    - name: Run Cucumber tests
      run: npm run cucumber
      env:
        CI: true

    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Cucumber test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: cucumber-report/
        retention-days: 30

    - name: Stop Docker containers
      if: always()
      run: docker-compose down
